name: Build and Push Docker Image

on:
  push:
    branches: [main]

env:
  USERNAME: ${{ vars.DOCKER_USERNAME }}
  IMAGE: ${{ vars.IMAGE_NAME }}
  PASS: ${{ secrets.DOCKER_PASSWORD }}
  TOKEN: ${{ secrets.WATCHTOWER_TOKEN }}
  ADDR: ${{ secrets.SERVER_IP }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Slooze App
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $USERNAME
          password: $PASS

      - name: Setting Version
        run: echo "VERSION=$(date +%s)" >>$GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $USERNAME/$IMAGE:$VERSION .
          docker tag $USERNAME/$IMAGE:$VERSION $USERNAME/$IMAGE:latest

      - name: Push Docker image
        run: |
          docker push $USERNAME/$IMAGE:$VERSION
          docker push $USERNAME/$IMAGE:latest

      - name: Trigger Deploy Webhook
        run: |
          curl -X POST \
          -H "Authorization: Bearer $TOKEN" \
           http://$ADDR:8080/v1/update
